-- MySQL Script generated by MySQL Workbench
-- Wed Nov 23 10:34:29 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema selectadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `selectadb` ;
CREATE SCHEMA IF NOT EXISTS `selectadb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `selectadb` ;

-- -----------------------------------------------------
-- Table `selectadb`.`cv_pipelines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`cv_pipelines` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`cv_pipelines` (
  `pipeline_id` INT NOT NULL,
  `pipline_name` VARCHAR(200) NULL,
  `pipeline_desc` VARCHAR(1000) NULL,
  `pipeline_properties` VARCHAR(500) NULL,
  PRIMARY KEY (`pipeline_id`),
  UNIQUE INDEX `pipline_name_UNIQUE` (`pipline_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectadb`.`process_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`process_stages` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`process_stages` (
  `process_id` INT NOT NULL,
  `stage_name` VARCHAR(100) NOT NULL,
  `pipeline_id` INT NOT NULL,
  `audit_time` TIMESTAMP NULL,
  `audit_user` VARCHAR(100) NULL,
  `stage_start` DATETIME NULL,
  `stage_end` DATETIME NULL,
  `stage_error` VARCHAR(1000) NULL,
  PRIMARY KEY (`process_id`, `stage_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectadb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`account` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`account` (
  `account_id` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `account_type` TIMESTAMP NOT NULL,
  PRIMARY KEY (`account_id`));


-- -----------------------------------------------------
-- Table `selectadb`.`process_selection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`process_selection` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`process_selection` (
  `selection_id` VARCHAR(45) NOT NULL,
  `account_id` VARCHAR(100) NOT NULL,
  `tax_id` INT NULL,
  `study_accession` VARCHAR(45) NULL,
  `run_accession` VARCHAR(45) NULL,
  `pipeline_name` VARCHAR(200) NOT NULL,
  `analysis_id` VARCHAR(45) NULL,
  `public` VARCHAR(45) NULL,
  `selection_provided_date` DATETIME NULL,
  `selection_to_info_start` DATETIME NULL,
  `selection_to_info_end` DATETIME NULL,
  `selection_to_info_error` VARCHAR(300) NULL,
  `audit_time` VARCHAR(45) NULL,
  `audit_user` VARCHAR(45) NULL,
  PRIMARY KEY (`selection_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectadb`.`process_attributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`process_attributes` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`process_attributes` (
  `process_id` INT NOT NULL,
  `attribute_key` VARCHAR(100) NULL,
  `attribute_value` VARCHAR(200) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectadb`.`selecta_rule_templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selectadb`.`selecta_rule_templates` ;

CREATE TABLE IF NOT EXISTS `selectadb`.`selecta_rule_templates` (
  `template_id` INT NOT NULL,
  `pipeline_id` VARCHAR(45) NULL,
  `template` VARCHAR(45) NULL,
  `master_attributes` VARCHAR(45) NULL,
  `all_attributes` VARCHAR(45) NULL,
  PRIMARY KEY (`template_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
