-- MySQL Script generated by MySQL Workbench
-- Thu Sep  1 15:10:29 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SELECTA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SELECTA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SELECTA` ;

-- -----------------------------------------------------
-- Table `SELECTA`.`INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`INFO` (
  `run_accession` VARCHAR(100) NOT NULL,
  `study_accession` VARCHAR(100) NOT NULL,
  `sample_accession` VARCHAR(100) NOT NULL,
  `experiment_accession` VARCHAR(100) NOT NULL,
  `fastq_ftp_pub` VARCHAR(400) NULL,
  `fastq_ftp_pri` VARCHAR(400) NULL,
  `fastq_md5_pub` VARCHAR(200) NULL,
  `fastq_md5_pri` VARCHAR(200) NULL,
  `fastq_bytes_pub` VARCHAR(200) NULL,
  `fastq_bytes_pri` VARCHAR(200) NULL,
  `ftp_pri_account` VARCHAR(100) NULL,
  `scientific_name` VARCHAR(200) NULL,
  `instrument_platform` VARCHAR(200) NULL,
  `library_layout` VARCHAR(200) NULL,
  `instrument_model` VARCHAR(200) NULL,
  `library_strategy` VARCHAR(200) NULL,
  `library_name` VARCHAR(200) NULL,
  `library_source` VARCHAR(200) NULL,
  `tax_id` INT NULL,
  `audit_time` TIMESTAMP NULL,
  `audit_user` VARCHAR(100) NULL,
  PRIMARY KEY (`run_accession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELECTA`.`CV_PIPELINES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`CV_PIPELINES` (
  `pipeline_id` INT NOT NULL,
  `pipline_name` VARCHAR(200) NULL,
  `pipeline_desc` VARCHAR(1000) NULL,
  `pipeline_owner` VARCHAR(45) NULL,
  `pipeline_contact` VARCHAR(45) NULL,
  PRIMARY KEY (`pipeline_id`),
  UNIQUE INDEX `pipline_name_UNIQUE` (`pipline_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELECTA`.`PROCESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`PROCESS` (
  `process_id` INT NOT NULL,
  `process_start` DATETIME NULL,
  `process_end` DATETIME NULL,
  `process_error` VARCHAR(1000) NULL,
  `audit_time` TIMESTAMP NULL,
  `audit_user` VARCHAR(100) NULL,
  PRIMARY KEY (`process_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELECTA`.`PROCESS_SELECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`PROCESS_SELECTION` (
  `process_id` INT NOT NULL,
  `pipeline_id` INT NOT NULL,
  `submission_date` DATETIME NOT NULL,
  `run_accession` VARCHAR(100) NOT NULL,
  `audit_time` TIMESTAMP NULL,
  `audit_user` VARCHAR(100) NULL,
  PRIMARY KEY (`process_id`),
  INDEX `fk_selecta_process_selection_selecta_process1_idx` (`submission_date` ASC),
  INDEX `fk_selecta_process_selection_selecta_info1_idx` (`run_accession` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELECTA`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`USER` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `SELECTA`.`RULES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELECTA`.`RULES` (
  `account_id` VARCHAR(100) NULL,
  `tax_id` INT NULL,
  `study_accession` VARCHAR(100) NULL,
  `run_accession` VARCHAR(100) NULL,
  `pipeline_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
